import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import type { BibliometricNetwork } from '../../domain/networkTypes';
import { generateDensityMap } from '../../services/networks/generateDensityMap';

export function DensityView({ network, topN }: { network: BibliometricNetwork; topN: number }) {
  const { t } = useTranslation(); const points = useMemo(() => generateDensityMap({ ...network, nodes: [...network.nodes].sort((a, b) => b.weight - a.weight).slice(0, topN) }), [network, topN]);
  const bounds = useMemo(() => { const xs = points.map((point) => point.x), ys = points.map((point) => point.y); return { minX: Math.min(...xs), maxX: Math.max(...xs), minY: Math.min(...ys), maxY: Math.max(...ys) }; }, [points]);
  const positioned = points.map((point) => ({ ...point, px: 55 + ((point.x - bounds.minX) / (bounds.maxX - bounds.minX || 1)) * 890, py: 55 + ((point.y - bounds.minY) / (bounds.maxY - bounds.minY || 1)) * 490 }));
  const labelThreshold = [...points].sort((a, b) => b.weight - a.weight)[Math.min(19, points.length - 1)]?.weight ?? 0;
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-[#071c35]"><svg id="wasabi-network-svg" viewBox="0 0 1000 600" className="h-auto min-h-[420px] w-full" role="img" aria-label={t('networks.densityLabel')}><defs><filter id="density-soft"><feGaussianBlur stdDeviation="18" /></filter><filter id="density-hot"><feGaussianBlur stdDeviation="10" /></filter><radialGradient id="density-outer"><stop offset="0" stopColor="#22d3ee" stopOpacity=".8" /><stop offset=".48" stopColor="#2563eb" stopOpacity=".55" /><stop offset="1" stopColor="#172554" stopOpacity="0" /></radialGradient><radialGradient id="density-middle"><stop offset="0" stopColor="#fef08a" stopOpacity=".95" /><stop offset=".38" stopColor="#84cc16" stopOpacity=".85" /><stop offset="1" stopColor="#10b981" stopOpacity="0" /></radialGradient><radialGradient id="density-core"><stop offset="0" stopColor="#ef4444" stopOpacity=".96" /><stop offset=".38" stopColor="#facc15" stopOpacity=".9" /><stop offset="1" stopColor="#facc15" stopOpacity="0" /></radialGradient><linearGradient id="density-scale"><stop offset="0" stopColor="#172554"/><stop offset=".3" stopColor="#2563eb"/><stop offset=".55" stopColor="#10b981"/><stop offset=".78" stopColor="#facc15"/><stop offset="1" stopColor="#ef4444"/></linearGradient></defs><rect width="1000" height="600" fill="#071c35"/><g filter="url(#density-soft)" style={{ mixBlendMode: 'screen' }}>{positioned.map((point) => <circle key={`outer-${point.id}`} cx={point.px} cy={point.py} r={point.radius * 1.45} fill="url(#density-outer)" opacity={.35 + point.intensity * .55}/>)}</g><g filter="url(#density-hot)" style={{ mixBlendMode: 'screen' }}>{positioned.map((point) => <circle key={`middle-${point.id}`} cx={point.px} cy={point.py} r={point.radius * .82} fill="url(#density-middle)" opacity={point.intensity}/>)}</g><g filter="url(#density-hot)" style={{ mixBlendMode: 'screen' }}>{positioned.filter((point) => point.intensity > .55).map((point) => <circle key={`core-${point.id}`} cx={point.px} cy={point.py} r={point.radius * .38} fill="url(#density-core)" opacity={(point.intensity - .4) / .6}/>)}</g><g>{positioned.filter((point) => point.weight >= labelThreshold).map((point) => <text key={`label-${point.id}`} x={point.px} y={point.py - 8} textAnchor="middle" fontSize={11 + point.intensity * 4} fontWeight="600" fill="white" stroke="#071c35" strokeWidth="3" paintOrder="stroke">{point.label.length > 30 ? `${point.label.slice(0, 30)}…` : point.label}</text>)}</g><g transform="translate(748 555)"><text x="0" y="-8" fill="white" fontSize="11">{t('networks.density.low')}</text><rect width="160" height="10" rx="5" fill="url(#density-scale)"/><text x="168" y="9" fill="white" fontSize="11">{t('networks.density.high')}</text></g></svg></div>;
}
