import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import type { BibliographicRecord } from '../../domain/bibliographicRecord';
import { recordLink } from '../../utils/bibliographicLink';

const PAGE_SIZE = 20;
export function CorpusTable({ records }: { records: BibliographicRecord[] }) {
  const { t } = useTranslation(); const [query, setQuery] = useState(''); const [page, setPage] = useState(0);
  const filtered = useMemo(() => { const normalized = query.trim().toLocaleLowerCase(); return normalized ? records.filter((record) => [record.title, record.authors.join(' '), record.sourceTitle, record.doi, record.keywords.join(' ')].some((value) => value?.toLocaleLowerCase().includes(normalized))) : records; }, [records, query]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const currentPage = Math.min(page, pageCount - 1); const shown = filtered.slice(currentPage * PAGE_SIZE, (currentPage + 1) * PAGE_SIZE);
  return <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><h3 className="text-xl font-bold text-slate-800">{t('dashboard.corpusTable')}</h3><p className="mt-1 text-sm text-slate-500">{t('dashboard.recordsFound', { count: filtered.length })}</p></div><label className="grid gap-1 text-sm font-semibold text-slate-700"><span>{t('dashboard.searchCorpus')}</span><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} className="rounded-lg border border-slate-200 px-3 py-2" /></label></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-100"><tr>{['title', 'authors', 'year', 'source', 'type', 'citations', 'access'].map((field) => <th key={field} className="px-4 py-3">{t(`dashboard.corpus.${field}`)}</th>)}</tr></thead><tbody>{shown.map((record) => { const link = recordLink(record); return <tr key={record.id} className="border-t border-slate-100"><td className="max-w-sm px-4 py-3 font-semibold">{link ? <a href={link} target="_blank" rel="noreferrer" className="text-wasabi-700 underline decoration-wasabi-200 underline-offset-2 hover:text-wasabi-900">{record.title || t('dashboard.corpus.openRecord')}</a> : record.title || '—'}</td><td className="max-w-xs px-4 py-3">{record.authors.join('; ') || '—'}</td><td className="px-4 py-3">{record.year ?? '—'}</td><td className="px-4 py-3">{record.sourceTitle ?? '—'}</td><td className="px-4 py-3">{record.documentType ?? '—'}</td><td className="px-4 py-3 text-right">{record.citationCount ?? '—'}</td><td className="px-4 py-3">{link ? <a href={link} target="_blank" rel="noreferrer" className="whitespace-nowrap font-sans font-semibold text-wasabi-700">{record.doi ? 'DOI ↗' : `${t('dashboard.corpus.page')} ↗`}</a> : '—'}</td></tr>; })}</tbody></table></div><div className="mt-4 flex items-center justify-end gap-3 font-sans text-sm"><button disabled={currentPage === 0} onClick={() => setPage((value) => Math.max(0, value - 1))} className="rounded-lg border border-slate-200 px-3 py-2 disabled:opacity-40">{t('common.previous')}</button><span>{t('common.pageOf', { page: currentPage + 1, total: pageCount })}</span><button disabled={currentPage >= pageCount - 1} onClick={() => setPage((value) => Math.min(pageCount - 1, value + 1))} className="rounded-lg border border-slate-200 px-3 py-2 disabled:opacity-40">{t('common.next')}</button></div></section>;
}
